### ISSUE TITLE
Generate test data for containers & pods within database

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#102]
## User story
1. As a developer
2. I need test data available within the database
3. So that I can quickly test or implement changes without connecting to a proxy instance

## Acceptance criteria
- [ ] Test data for containers includes: id, name, image, health, volumes, ports,
- [ ] Test data for pods includes: id, name, health, containers
- [ ] Test data is stored in database

## Linked Issues
- **Blocked by:**
- **Related to:**
   - #64  
- **Implements**

## Additional information
- Provide setup script which is executed based on a passed flag on database startup
- This could be also used for frontend testing

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies
