### ISSUE TITLE
Create health indicator component

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#105]
## User story
1. As a user
2. I want to see the health state of a single resource
3. So that I can quikly identify unhealthy components

## Acceptance criteria
- [x] Display the state as both colour and text
- [x] Text is always easily readable
- [x] Green on successfully terminated
- [x] Red on terminated with error
- [x] Green on running
- [x] Yellow on waiting
- [x] Color hex value is document at  [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)

## Additional Information
- The implementation is done as reusable, configurable component
- This component will be used in several places (container lists, container detail pages, pod lists,...)
- It does not have to be coupled to real data, implement it by passing the value tot he component

## Linked Issues
- **Blocked by:**
- **Related to:**
- **Implements**

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies
