### ISSUE TITLE
Implement CICD

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#107]
## User story
1. As a developer
2. I want / need a CICD pipeline
3. So that I can easily build, test and release new features.

## Acceptance criteria
- [x] Proxy container is build
- [x] Frontend container is build
- [x] Integration testing is prepared with spinning up Kubernetes
- [x] #28 is implemented

## Linked Issues
- **Blocked by:**
- **Related to:**
- **Implements:**
   - #28  

## Additional information
- none

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies
