### ISSUE TITLE
Create final release plan

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#17]
## Task
- [ ] Fill in the release plan section of your planning documents.
- [ ] Ensure that the burn-down chart displays correctly.
- [ ] For the mid-project release plan, you only have to fill in the mid-project release.
- [ ] For the final project release plan, you now need to fill in both project releases.
