### ISSUE TITLE
Collect persistent volumes from cluster

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#177]
## User story

1. As a developer
2. I want / need to collect and persist information about volumes
3. So that those information can be displayed in the frontend

## Acceptance criteria

- [x] Claimed persistent volumes are collected
- [x] Unused/not claimed persistent volumes are collected
- [x] Claimed persistent volumes are linked to the parent resources
- [x] All information collected is persisted in the database
- [x] Claimed volumes have a name and path based on volume mounts of the parent

## Linked Issues

- **Blocked by:**
- **Related to:**
- **Implements**

## Additional information

- Concentrate on Kubernetes persistent volumes, no external volume resources 

## Definition of done (DoD)

- Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
- Implementation is unit tested
- Code documentation updated (jsdoc or godoc?)
- Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
- Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria

- Feature has been fully implemented
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Pull request to "develop" branch is merged & closed
- Bill of materials is updated with new dependencies

**Comment by lifesbest23** [comment]
Generating relevant test data for the new cases are still to be done.

**Comment by jandegen** [comment]
Not merged yet
