### ISSUE TITLE
View nodes detail page

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#190]
## User story

1. As a user 
2. I want / need to view nodes in detail
3. So that I can gather all relevant information about that node

## Acceptance criteria

The page contains:
- [ ] Name
- [ ] Max CPU capacity
- [ ] Max RAM capacity
- [ ] Current CPU capacity
- [ ] Current RAM capacity
- [ ] Maximum number of pods running on this node
- [ ] Current number of pods running on this node
- [ ] A health indicator showing the health state of the node
- [ ] List of running pods with link the the pods detail page
- [ ] Each pod has a health indicator

## Linked Issues

- **Blocked by:**
- **Related to:**
   - #156 
   - #189 
- **Implements**

## Additional information

- none

## Definition of done (DoD)

- Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
- Implementation is unit tested
- Code documentation updated
- Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
- Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria

- Feature has been fully implemented
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Pull request to "develop" branch is merged & closed
- Bill of materials is updated with new dependencies
