### ISSUE TITLE
Research failure stories of Kubernetes

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#191]
## User story

1. As a developer
2. I want / need to know about failure stories of Kubernetes applications
3. So that I can figure out important information about e.g. replica sets

## Acceptance criteria

- [ ] Report contains important information which should be monitored
- [ ] A wiredraft for the important information
- [ ] Document findings in Confluence

## Linked Issues

- **Blocked by:**
- **Related to:**
- **Implements**

## Additional information

- none

## Definition of done (DoD)

- Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
- Implementation is unit tested
- Code documentation updated
- Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
- Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria

- Feature has been fully implemented
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Pull request to "develop" branch is merged & closed
- Bill of materials is updated with new dependencies

**Comment by njochens** [comment]
https://k8s.af/

**Comment by jandegen** [comment]
https://amos-p4.atlassian.net/l/cp/1Rps8hSc

**Comment by jandegen** [comment]
![Image](https://github.com/amosproj/amos2023ss04-kubernetes-inventory-taker/assets/81998094/6b5f9f88-ac13-4460-93d9-603d55e00efe)

**Comment by jandegen** [comment]
![Image](https://github.com/amosproj/amos2023ss04-kubernetes-inventory-taker/assets/81998094/6cd55923-32ee-48e3-bd2f-ca5ae5722f54)

**Comment by PhlppKrmr** [comment]
![Image](https://github.com/amosproj/amos2023ss04-kubernetes-inventory-taker/assets/54808295/4b29e605-f6c5-49a4-b620-40ade8496577)
