### ISSUE TITLE
Update test data for demo day

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#192]
## User story

1. As a developer
2. I want / need to update the current test data
3. So that I can showcase different scenarios on demo day

## Acceptance criteria

- [ ] Demo data contains healthy and unhealthy containers
- [ ] Demo data contains healthy and unhealthy pods
- [ ] Includes test data for volumes

## Linked Issues

- **Blocked by:**
- **Related to:**
   - #191 
   - #102 
- **Implements**

## Additional information

- none

## Definition of done (DoD)

- Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
- Implementation is unit tested
- Code documentation updated
- Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
- Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria

- Feature has been fully implemented
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Pull request to "develop" branch is merged & closed
- Bill of materials is updated with new dependencies
