### ISSUE TITLE
Display child container of pods at the detail page

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#53]
## User story
1. As a user
2. I want / need at a pods detail page all assigned containers of this pod
3. So that I can quickly see which containers are running at this pod

## Acceptance criteria
- [ ] The detail page shows all assigned containers as list
- [ ] If the list is to long, it is paginated
- [ ] The containers also have the health indicator
- [ ] The user can quickly navigate from the list to a containers detail page

## Linked issues
- **Related:** #54 

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by jandegen** [comment]
Already done
