### ISSUE TITLE
Collect deployments from cluster

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#56]
## User story
1. As a developer
2. I want / need to collect and persist information about deployments
3. So that I can display them in the frontend

## Acceptance criteria
- [ ] The proxy collects the metadata about the deployment
- [ ] The proxy collects the health status based on the DeploymentStatus 
- [ ] The proxy collects information about replicas of a deployment
- [ ] The proxy collects the strategy of the deployment
- [ ] All information is persisted within the database as additional table
- [ ] Information is updated periodically based on the update parameter

## Linked Issues:
- **Related to:** #55 

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release
