### ISSUE TITLE
Create software architecture description

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#8]
## Task
Prepare a description of the planned software architecture; include
- [ ] An overview diagram of runtime components (one page)
- [ ] An overview diagram of code components (one page)
- [ ] A summary of the underlying technology stack (one page)
- [ ] A textual explanation of the diagrams and choices (one page)
