### ISSUE TITLE
Track changes with watchers

### ISSUE THREAD

**Issue by PhlppKrmr** [amosproj/amos2023ss04-kubernetes-inventory-taker#85]
## User story
1. As a developer
2. I want / need to track changes to resources
3. So that I can persist them in the database

## Acceptance criteria
- [x] All resources of configured resource types are tracked by Kubernetes watchers
- [x] Event-based architecture
- [x] Changes are persisted in the database
- [ ] Container Id is stored in database

## Linked Issues
- **Blocked by:**
- **Related to:**
    - #43 
    - #44
    - #54
    - #56 
- **Implements**

## Additional information
- Create a reusable component
- No need to collect everything, just the base implementation for now
- For now only containers, in the future there will be additional watchers for the othere resources

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by jandegen** [comment]
Requires additional implement. First implementation of watchers done but needs adaption to database

**Comment by jandegen** [comment]
Delayed due to illness. 
Questions regarding
 * Kubernetes API integrated into database
 * Containers are challenging

**Comment by lifesbest23** [comment]
Open:

- Containers need to be written to DB
- Documentation needs to be finished

**Comment by jandegen** [comment]
Already contains implementation for nodes, services. So additional effort was done which caused the bigger real size.
